### ISSUE TITLE
table.clone() won't work with Lua <5.3

### ISSUE THREAD

**Issue by JuanjoSalvador** [vronc/Lua-Dungeon-Generator#1]
I'm using this to generate random dungeons for a sample game I'm working on, but my engine (LÖVE2D) uses Lua 5.1 instead of 5.3, so some features are not available for us.

I made some hacks on the library in order to make it works with LÖVE. This is not an issue itself but an advice for the future.

```lua
function table.clone(org)
  local newTable = {}
  for k,v in pairs(org) do
      newTable[k] = v
  end
  return newTable
end
```

works better than

```lua
function table:clone(org)
  return {table.unpack(org)}
end
```

And makes it compatible with previous versions. This is the only issue I found.

**Comment by vronc** [comment]
Hi, @JuanjoSalvador! Happy to hear you find this project useful! PR merged ✅
